name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy and update
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$DROPLET_IP << EOF
            cd /home/krishnanunnir/manhwarepo
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            echo $SSH_PASSWORD | sudo -S systemctl restart manhwarepo
            echo $SSH_PASSWORD | sudo -S systemctl restart nginx
          EOF
